server:
  port: 10002

spring:
  application:
    name: cloud-payment-hystrix-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.232:3306/springcloud2020?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1



mybatis:
  # 实体类的存放路径
  type-aliases-package: com.github.greekpanda.springcloud2020.entities
  mapper-locations: classpath:mapper/*.xml


eureka:
  client:
    # 表示是否将自己注册进EurekaServer，默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true
    fetch-registry: true
    service-url:
      # 单机版
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
      # 集群版
      # defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: hystrix-payment10002
    # 访问路径可以显示ip地址
    prefer-ip-address: true

#  redis:
#    cluster:
#      nodes:
#        - 192.168.0.112:7001
#        - 192.168.0.112:7002
#        - 192.168.0.112:7003
#        - 192.168.0.112:7004
#        - 192.168.0.112:7005
#        - 192.168.0.112:7006